source ./install_scripts/bash_colors.sh

echo -e "\n${NC}Begin Terminal Colors Test!\n"

echo -e "\n${NC}Basic Colors"
echo -e "${BLACK}Black${NC}"
echo -e "${RED}Red${NC}"
echo -e "${GREEN}Green${NC}"
echo -e "${YELLOW}Yellow${NC}"
echo -e "${BLUE}Blue${NC}"
echo -e "${PURPLE}Purple${NC}"
echo -e "${CYAN}Cyan${NC}"
echo -e "${WHITE}White${NC}"

echo -e "\n${NC}Bold Colors"
echo -e "${B_BLACK}Black${NC}"
echo -e "${B_RED}Red${NC}"
echo -e "${B_GREEN}Green${NC}"
echo -e "${B_YELLOW}Yellow${NC}"
echo -e "${B_BLUE}Blue${NC}"
echo -e "${B_PURPLE}Purple${NC}"
echo -e "${B_CYAN}Cyan${NC}"
echo -e "${B_WHITE}White${NC}"

echo -e "\n${NC}Underline Colors"
echo -e "${U_BLACK}Black${NC}"
echo -e "${U_RED}Red${NC}"
echo -e "${U_GREEN}Green${NC}"
echo -e "${U_YELLOW}Yellow${NC}"
echo -e "${U_BLUE}Blue${NC}"
echo -e "${U_PURPLE}Purple${NC}"
echo -e "${U_CYAN}Cyan${NC}"
echo -e "${U_WHITE}White${NC}"

echo -e "\n${NC}Background Colors"
echo -e "${BG_BLACK}Black${NC}"
echo -e "${BG_RED}Red${NC}"
echo -e "${BG_GREEN}Green${NC}"
echo -e "${BG_YELLOW}Yellow${NC}"
echo -e "${BG_BLUE}Blue${NC}"
echo -e "${BG_PURPLE}Purple${NC}"
echo -e "${BG_CYAN}Cyan${NC}"
echo -e "${BG_WHITE}White${NC}"

echo -e "\n${NC}High Intensity Colors"
echo -e "${I_BLACK}Black${NC}"
echo -e "${I_RED}Red${NC}"
echo -e "${I_GREEN}Green${NC}"
echo -e "${I_YELLOW}Yellow${NC}"
echo -e "${I_BLUE}Blue${NC}"
echo -e "${I_PURPLE}Purple${NC}"
echo -e "${I_CYAN}Cyan${NC}"
echo -e "${I_WHITE}White${NC}"

echo -e "\n${NC}Bold High Intensity Colors"
echo -e "${BI_BLACK}Black${NC}"
echo -e "${BI_RED}Red${NC}"
echo -e "${BI_GREEN}Green${NC}"
echo -e "${BI_YELLOW}Yellow${NC}"
echo -e "${BI_BLUE}Blue${NC}"
echo -e "${BI_PURPLE}Purple${NC}"
echo -e "${BI_CYAN}Cyan${NC}"
echo -e "${BI_WHITE}White${NC}"

echo -e "\n${NC}High Intensity Background Colors"
echo -e "${IBG_BLACK}Black${NC}"
echo -e "${IBG_RED}Red${NC}"
echo -e "${IBG_GREEN}Green${NC}"
echo -e "${IBG_YELLOW}Yellow${NC}"
echo -e "${IBG_BLUE}Blue${NC}"
echo -e "${IBG_PURPLE}Purple${NC}"
echo -e "${IBG_CYAN}Cyan${NC}"
echo -e "${IBG_WHITE}White${NC}"

echo -e "\n${NC}End Terminal Colors Test!\n"