source ./bash_colors.sh

echo -e "\n${NC}Begin Terminal Colors Test!\n"

echo -e "\n${NC}Basic Colors"
echo -e "${BLACK}Black${NC}"
echo -e "${RED}Red${NC}"
echo -e "${GREEN}Green${NC}"
echo -e "${YELLOW}Yellow${NC}"
echo -e "${BLUE}Blue${NC}"
echo -e "${PURPLE}Purple${NC}"
echo -e "${CYAN}Cyan${NC}"
echo -e "${WHITE}White${NC}"

echo -e "\n${NC}Bold Colors"
echo -e "${BBLACK}Black${NC}"
echo -e "${BRED}Red${NC}"
echo -e "${BGREEN}Green${NC}"
echo -e "${BYELLOW}Yellow${NC}"
echo -e "${BBLUE}Blue${NC}"
echo -e "${BPURPLE}Purple${NC}"
echo -e "${BCYAN}Cyan${NC}"
echo -e "${BWHITE}White${NC}"

echo -e "\n${NC}Underline Colors"
echo -e "${UBLACK}Black${NC}"
echo -e "${URED}Red${NC}"
echo -e "${UGREEN}Green${NC}"
echo -e "${UYELLOW}Yellow${NC}"
echo -e "${UBLUE}Blue${NC}"
echo -e "${UPURPLE}Purple${NC}"
echo -e "${UCYAN}Cyan${NC}"
echo -e "${UWHITE}White${NC}"

echo -e "\n${NC}Background Colors"
echo -e "${On_BLACK}Black${NC}"
echo -e "${On_RED}Red${NC}"
echo -e "${On_GREEN}Green${NC}"
echo -e "${On_YELLOW}Yellow${NC}"
echo -e "${On_BLUE}Blue${NC}"
echo -e "${On_PURPLE}Purple${NC}"
echo -e "${On_CYAN}Cyan${NC}"
echo -e "${On_WHITE}White${NC}"

echo -e "\n${NC}High Intensity Colors"
echo -e "${IBLACK}Black${NC}"
echo -e "${IRED}Red${NC}"
echo -e "${IGREEN}Green${NC}"
echo -e "${IYELLOW}Yellow${NC}"
echo -e "${IBLUE}Blue${NC}"
echo -e "${IPURPLE}Purple${NC}"
echo -e "${ICYAN}Cyan${NC}"
echo -e "${IWHITE}White${NC}"

echo -e "\n${NC}Bold High Intensity Colors"
echo -e "${BIBLACK}Black${NC}"
echo -e "${BIRED}Red${NC}"
echo -e "${BIGREEN}Green${NC}"
echo -e "${BIYELLOW}Yellow${NC}"
echo -e "${BIBLUE}Blue${NC}"
echo -e "${BIPURPLE}Purple${NC}"
echo -e "${BICYAN}Cyan${NC}"
echo -e "${BIWHITE}White${NC}"

echo -e "\n${NC}High Intensity Background Colors"
echo -e "${On_IBLACK}Black${NC}"
echo -e "${On_IRED}Red${NC}"
echo -e "${On_IGREEN}Green${NC}"
echo -e "${On_IYELLOW}Yellow${NC}"
echo -e "${On_IBLUE}Blue${NC}"
echo -e "${On_IPURPLE}Purple${NC}"
echo -e "${On_ICYAN}Cyan${NC}"
echo -e "${On_IWHITE}White${NC}"

echo -e "\n${NC}End Terminal Colors Test!\n"